---

- name: Download build artifact from sftp_server_name to webapp_name path
  shell: >
    (
    echo "get {{ webapp_name }}/{{ webapp_name }}.war /usr/local/{{ webapp_name }}/webapps/{{ webapp_name }}.war" ;
    echo "bye"
    ) | sftp -oIdentityFile={{ ansible_ident_file }} -b - {{ sftp_username}}@{{ sftp_server_name }}:{{ sftp_path }}
  args:
    executable: /bin/bash
  register: sftp_status
  ignore_errors: yes

- name: Handle any SFTP download failures
  include: handle_failure.yml
  when: sftp_status.rc != 0

- name: Set ownership on build artifact
  file:
    path: "/usr/local/{{ webapp_name }}/webapps/{{ webapp_name }}.war"
    owner: "{{ webapp_name }}"
    group: "{{ webapp_name }}"

- name: Start Tomcat Instance
  service:
    name: "{{ webapp_name }}"
    enabled: "yes"
    state: "started"
