---

- name: Determine if this is a new install of webapp_name
  stat:
    path: "/usr/local/{{ webapp_name }}"
  register: webapp_path

- name: Back-up webapp if it already exists
  import_tasks: backup_webapp.yml
  when: webapp_path.stat.exists | bool

- name: Install the webapp
  import_tasks: install_webapp.yml
